### ISSUE TITLE
Template functions related to local registry no longer work in Config resource

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kots#1126]
With KOTS 1.18.1, I was using a pattern like
```
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: cd4pe-config
spec:
  groups:
  - name: setup
    title: Setup
    items:
    - name: registry_hostname
      type: text
      title: Local registry hostname
      required: true
      when: '{{repl and IsKurl HasLocalRegistry}}'
    - name: registry_endpoint
      type: text
      title: Local registry endpoint
      default: repl{{ConfigOption "registry_hostname"}}
      when: '{{repl and IsKurl HasLocalRegistry}}'
```
to provide config for using the local registry kURL sets up in an airgap install. When I upgrade to KOTS 1.19.1 (or later), `HasLocalRegistry` now always returns false and these config items no longer show up. It continues to work correctly when deploying resources.

This seems to be a regression around how KOTS renders Config in the Config tab.
