### ISSUE TITLE
BUG: Unable to generate a file diff for release when helm dependency is removed

### ISSUE THREAD

**Issue by stefreak** [replicatedhq/kots#3143]
# Steps to reproduce
1. Create a local helm chart as follows

```
apiVersion: v2
name: my-charts
description: Helm charts for my Replicated App
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
  - name: kibana
    version: 7.16.2
    repository: https://helm.elastic.co
  - name: vault
    version: 0.20.0
    repository: https://helm.releases.hashicorp.com
```

2. Create a Replicate release that contains `my-charts` as described in [Adding a helm chart to a release guide](https://docs.replicated.com/vendor/helm-release#add-a-helm-chart-to-a-release)
3. Install the release
4. Remove the vault dependency from the helm chart
5. Create another release that contains `my-charts` (without vault)
6. Update to the second release
7. Look at the diff

# Observed behaviour
```
failed to diff: failed to kustomize archive charts dir: failed to kustomize /tmp/kotsadm2105596108/overlays/downstreams/this-cluster/charts/my-charts/charts/vault/kustomization.yaml: kustomize /tmp/kotsadm2105596108/overlays/downstreams/this-cluster/charts/my-charts/charts/vault/kustomization.yaml: "2022/09/02 13:51:15 evalsymlink failure on '/tmp/kotsadm2105596108/base/charts/my-charts/charts/vault' : lstat /tmp/kotsadm2105596108/base/charts/my-charts/charts/vault: no such file or directory\nError: accumulating resources: recursed accumulation of path '/tmp/kotsadm2105596108/overlays/midstream/charts/my-charts/charts/vault': accumulating resources: accumulating resources from '../../../../../../base/charts/my-charts/charts/vault': evalsymlink failure on '/tmp/kotsadm2105596108/base/charts/my-charts/charts/vault' : lstat /tmp/kotsadm2105596108/base/charts/my-charts/charts/vault: no such file or directory\n"
```

Additionally, the error seems to persist for following releases, even when vault is not included in all of them anymore.

# Expected behaviour
You should be able to see the diff.
