### ISSUE TITLE
[Feature Request] RecursiveMerge for multiple optional array values

### ISSUE THREAD

**Issue by RyanHolstien** [replicatedhq/kots#3160]
### Problem
I have the following set-up:

```
  optionalValues: 
   - when: '{{repl (ConfigOptionNotEquals `NAME1` ``)}}'
      recursiveMerge: true
      values:
        top-level:
          intermediate-level:
            - name: VALUE_1
              value: "repl{{ ConfigOption `NAME1`}}"
    - when: '{{repl (ConfigOptionNotEquals `NAME2` ``)}}'
      recursiveMerge: true
      values:
        top-level:
          intermediate-level:
            - name: VALUE_2
              value: "repl{{ ConfigOption `NAME2`}}"
```

in this scenario, only VALUE_2 appears, this appears to be due to the merge logic here: https://github.com/replicatedhq/kots/blob/main/kotskinds/apis/kots/v1beta1/helmchart_types.go#L251 not accounting for array types with multiple values being appended, instead treating them as full overwrites for the key due to their lack of subobject keys.

### Feature Request
I would like to have both of these values appended into the intermediate-level array field, having the final value be the superset of values.top-level.intermediate-level and optionalValues.top-level.intermediate-level(VALUE_1, VALUE_2). Current workaround is to include additional conditional logic covering all scenarios possible which for 2 values is reasonable(1 && !2, 2 && !1, 1 && 2, !1 && !2), but can quickly increase in conditional logic for larger numbers of such fields resulting in a lot of bloat. I understand that there are some scenarios where the current behavior may be desired, so totally okay with this needing another optional field similar to recursiveMerge to enable the behavior.
