### ISSUE TITLE
Collect app=csi-* pod logs running in the rook/ceph namespace

### ISSUE THREAD

**Issue by banjoh** [replicatedhq/kots#3318]
At the moment, the [default support bundle spec](https://github.com/replicatedhq/kots/blob/main/pkg/supportbundle/defaultspec/spec.yaml) is missing logs from the `app=csi-*` pods. This are necessary as well when investigating storage issues

Is there a reason why we cannot collect all logs from the `rook-ceph` namespace? This will reduce the need on maintaining the spec i.e no need to add/remove pod field selectors. The spec below does just that

```yaml
    - logs:
        collectorName: rook-ceph-logs
        namespace: rook-ceph
        name: kots/rook
```
