### ISSUE TITLE
Images only referenced in preflight check collectors are not included in airgap packages

### ISSUE THREAD

**Issue by laverya** [replicatedhq/kots#501]
```
apiVersion: troubleshoot.replicated.com/v1beta1
kind: Preflight
metadata:
  name: airgap-preflight-checks
spec:
  analyzers:
    - textAnalyze:
        checkName: a name
        fileName: ping.txt/run-ping.log
        regexGroups: '(?P<Transmitted>\d+) packets? transmitted, (?P<Received>\d+) packets? received, (?P<Loss>\d+\.\d+)% packet loss'
        outcomes:
          - pass:
              when: "Loss < 5.0"
              message: google.com resolves correctly
          - fail:
              message: High packet loss  
  collectors:
    - run:
        collectorName: "run-ping"
        image: busybox:1
        name: ping.txt
        namespace: default
        command: ["ping"]
        args: ["-w", "5", 'google.com']
        imagePullPolicy: IfNotPresent
```
the 'busybox:1' image is not pulled, causing the preflight check to spin forever.
