### ISSUE TITLE
Jobs leave orphaned pods

### ISSUE THREAD

**Issue by divolgin** [replicatedhq/kots#534]
Create a release with a job that has a hardcoded and and a delete policy hook

```
apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
  annotations:
    "kots.io/hook-delete-policy": "hook-succeeded, hook-failed"
```

When a new version is shipped, the Job object is deleted successfully, but the pod is left on the system
