### ISSUE TITLE
additionalNamespaces: kotsadm-replicated-registry secret not propagated if all containers are public

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#613]
If an application's workloads all consist of only public images, it appears that the kotsadm-replicated-registry secret does not get propagated to any namespaces listed in `additionalNamespaces`

See this kotsapp for reference: https://github.com/replicatedhq/kotsapps/compare/master...dexhorthy:multi-namespace

```shell
 kubectl kots install multi-namespace/multi-namespace
```

After install, run `kubectl get secret -n hardcoded` and see it's missing. If you swap to using a private image, the secret will get propagated.

```yaml
apiVersion: kots.io/v1beta1
kind: License
metadata:
  name: mnsbigbank
spec:
  licenseID: 1aoJdIu8IJAmM2kCT6bYDSZmtYv
  licenseType: trial
  customerName: MNS BIG BANK
  appSlug: multi-namespace
  channelName: multi-namespace
  licenseSequence: 1
  endpoint: 'https://replicated.app'
  entitlements:
    expires_at:
      title: Expiration
      description: License Expiration
      value: ''
      valueType: String
  isGitOpsSupported: true
  isSnapshotSupported: true
  signature: >-
    eyJsaWNlbnNlRGF0YSI6ImV5SmhjR2xXWlhKemFXOXVJam9pYTI5MGN5NXBieTkyTVdKbGRHRXhJaXdpYTJsdVpDSTZJa3hwWTJWdWMyVWlMQ0p0WlhSaFpHRjBZU0k2ZXlKdVlXMWxJam9pYlc1elltbG5ZbUZ1YXlKOUxDSnpjR1ZqSWpwN0lteHBZMlZ1YzJWSlJDSTZJakZoYjBwa1NYVTRTVXBCYlUweWEwTlVObUpaUkZOYWJYUlpkaUlzSW14cFkyVnVjMlZVZVhCbElqb2lkSEpwWVd3aUxDSmpkWE4wYjIxbGNrNWhiV1VpT2lKTlRsTWdRa2xISUVKQlRrc2lMQ0poY0hCVGJIVm5Jam9pYlhWc2RHa3RibUZ0WlhOd1lXTmxJaXdpWTJoaGJtNWxiRTVoYldVaU9pSnRkV3gwYVMxdVlXMWxjM0JoWTJVaUxDSnNhV05sYm5ObFUyVnhkV1Z1WTJVaU9qRXNJbVZ1WkhCdmFXNTBJam9pYUhSMGNITTZMeTl5WlhCc2FXTmhkR1ZrTG1Gd2NDSXNJbVZ1ZEdsMGJHVnRaVzUwY3lJNmV5SmxlSEJwY21WelgyRjBJanA3SW5ScGRHeGxJam9pUlhod2FYSmhkR2x2YmlJc0ltUmxjMk55YVhCMGFXOXVJam9pVEdsalpXNXpaU0JGZUhCcGNtRjBhVzl1SWl3aWRtRnNkV1VpT2lJaUxDSjJZV3gxWlZSNWNHVWlPaUpUZEhKcGJtY2lmWDBzSW1selIybDBUM0J6VTNWd2NHOXlkR1ZrSWpwMGNuVmxMQ0pwYzFOdVlYQnphRzkwVTNWd2NHOXlkR1ZrSWpwMGNuVmxmWDA9IiwiaW5uZXJTaWduYXR1cmUiOiJleUpzYVdObGJuTmxVMmxuYm1GMGRYSmxJam9pV21sbFZtMUdXakpKTHk4MlowRTVSRkJRWVZBeFJ5dFVMMUI1VVd4emJHNVFLelZDWjFoRGJqTmFWQ3RuZFUxWmR5dHJTVkJSUmpRNVVVbHpiVzF2Wm1GQlVXbExNR1J4VkUxelkySmFiaTlJWWpaMGRXWlVkblJwUTNjNGJTdGtSbGcwTURWV1UwTTNPWEpFVjBkb2JpOU5UVmxoVTJkRmRHdFFiR3hYTjBKU1YyOW1lRVJhSzBOV1YzbExkR05xUTFFMFpHTXhVWFl6VUVSdWNISnJiSFIyUTBoc1pUbDFaR1ozTmtOUWRWcDRVVms1TDFSNFdFWllaVFY1VWt0d1ZVSkNaVkpQWkZBMFRta3ZPWFpCWlcxTmRXbHZMMnh6TlRVdlRtVlhRa3cyVVU0eWRUbDNNbEJsUm1zM1FtNHZhSE00TWpOb1FVNDBaVEJWYm5kUWRIZHliVzE1Y1RSTFdHdFVZMDVTYm5Ob2EwbHBTM2MxYTNkcVpWaE9aMlJUWWxBM1JqUkdOMlJxTDB3MU16ZGxNbkZRVlhGM04wdHZTa05HTUZkR1MyaHFhMjVIZWxKWlZGZzVaR3BKZGpBNU1FTm5hR2wzUFQwaUxDSndkV0pzYVdOTFpYa2lPaUl0TFMwdExVSkZSMGxPSUZCVlFreEpReUJMUlZrdExTMHRMVnh1VFVsSlFrbHFRVTVDWjJ0eGFHdHBSemwzTUVKQlVVVkdRVUZQUTBGUk9FRk5TVWxDUTJkTFEwRlJSVUYyWjJob2IyWnNOVlpTT1hWUk1WY3hORUZRZVZ4dU5HOVZOekF3UWxKSmJYTnFTbnBvTldaR1prbFZkakY1YWtZM1ZsWm5jUzlLU21OVGRubGxTRlZNTmxsTlEySXJRbFpJWVZCTmFIRlFNalpYWW1WUVNWeHVTVVpoYTJwTmNTc3ZjMHBIVW5SSlNrNTFOakZ3YkdWU1FYQnJWM0J5ZEZSclRIZFZObEZGYmtvNVpYVTVkbUpyVDI4clQzRkpOMUpQV0RnM2RETnBNRnh1ZVRoSWNYbEJOR0ZNZDIxcE1sWnhPRTV0U1dwMGJrWklSa0Z4TVdGQ00xRjRlVGhNTlVWNlQza3dkeTlKTjFGbFVVWlZjVkphYVhKM1ptSXlkRVFyYzF4dWIyUXpiMEkzUlc5eE16WkhLMkpPT1VFd1lrSnBaM0JqUmlzdldHUkNSemd2YjFSMGFtbzJabHBXYm5OU1NHcFBUSFZpVDJZMmVrNW9RV3ByYnpkdGRseHVOVWxOTjNvMmVVOWlkRXd4TDFoaVRucHRPVFpZUmtKdVJqRnFVbkZyU1ZGWE1FWkNOMUpQU25SWWQyVlphbkJsVDBJd2MzTlRSMnhPZFhKUmJXWndhMXh1ZEhkSlJFRlJRVUpjYmkwdExTMHRSVTVFSUZCVlFreEpReUJMUlZrdExTMHRMVnh1SWl3aWEyVjVVMmxuYm1GMGRYSmxJam9pWlhsS2VtRlhaSFZaV0ZJeFkyMVZhVTlwU25WaVIxcDNaV3BLVlZZeU1UUmlSRmt5VGxWc01tRkZSbUZrV0doT1RtNWFZVTFJUlhsYWVrMTJUa001U0U5WFZuUmhhM2gxWld0Sk1WbHFaRzlQU0ZKRFdsaE9URnBzUWpCamJtaFRWVk00ZVdWdWFGSlNSazVDWWxVeFExRlhValJVTWtwd1UxVnpOV05YT1hsaVYyTTBWRWRuTTFOSE9VeFRSRlY2V1ZVMVVrNXJOSEpUYW1SNlZWaE9lRk5HVWpSVmVtUkdaRzV2TldOV1JuZFdNVlo1VWtST1dsZEdRbHBrTURsb1pVWktRMWxYTUhKak1VbzBZMWhPY1ZZeWFIUldWbFV4VVRJMWMxSXliRkJpU0dSVVRrZGtNbVJYT1hKVWJHeENUa1JPYTFacmVHbGFWa3BIVWtkdmVHTXdXVEZXTTBaUVZVVkpNVmRYT1Zaa2FsWnVZM2s1V1dOSGJHcFRWVEZRWkd0emQyUldaSGRUYTA1T1VXdHNXVnB1Vm5KVVNFcEdVekpPVjFGcVNtaE5WV1JzWWtkU1QxWnFhRXhVYXpWclRsWm9UVkZYVmxkVk0xWm9VbGRHWVdGdVJrSldiWEJDWkc1Q2FHTkVUbTVVVm1oT1kyeHdkazVWYUc5TlV6bHFVVEp2TkZNeU1VTmxWMFpXVkcxVk1sbHJkSEJhV0VwTVVXeENTVlJWTVVwVmEyTjVWMnQ0VDFWSE5ESlhWMFo0WkVWb01FNUhiSEpOVkVsMlYxUk5NRTFGTVZwTk1rWkdUVlpzTkU1NlZsaGxSMmhzV2xVMVZWUlZSVGxRVTBselNXMWtjMkl5U21oaVJYUnNaVlZzYTBscWIybFpiVkpzV2xSVk1rNVVXWGRaTWxwcFRrUk9hazlYU1hsUFIwcHRUMVJvYkZsWFRtaGFiVVV5VGtSWmFXWlJQVDBpZlE9PSJ9
```
