### ISSUE TITLE
HelmChart objects do not support kots.io/when

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#677]
```
apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: nginx-ingress
  annotations:
    kots.io/when : '{{repl IsKurl }}'
```

This does not cause the chart to be excluded conditionally, it is always included

I know I have an alternative in `spec.exclude` but it would make more sense to have `HelmChart` spec match the pattern that all other resources support.

```
apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: nginx-ingress
spec:
  exclude: '{{repl (Not IsKurl)}}'
```
