### ISSUE TITLE
Ability to run "kots install" without requesting cluster admin permissions

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#768]
Currently, `kots install` creates a number of `ClusterRole`, `ServiceAccount`, and `ClusterRoleBinding` objects that give workloads like `kotsadm`, `kotsadm-api` and `kotsadm-operator` a fairly large scope of permission across the cluster. For example, this is the role given to kotsadm-operator presently:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    kots.io/backup-type: admin-console
    kots.io/kotsadm: "true"
  name: kotsadm-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
```

As I understand it, it is a goal of KOTS to be able to run in a single namespace of a multi-tenant cluster, without needing to reach across Kubernetes namespaces to read or write data.
