### ISSUE TITLE
Config/App: many fields in kots.io/v1beta1 Application do not support templating

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/kots#771]
There  are a few fields in the Application object that do not seem to support `repl{{` templating. In particular, dashboard links and statusInformers cannot be dynamically configured.

```
---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: myapp
spec:
  title: My App
  icon: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  descriptor:
    links:
      - description: Core
        url: https://{{repl ConfigOption "domain" }}
      - description: Administration
        url: https://{{repl ConfigOption "domain" }}/admin
      - description: Documentation
        url: https://{{repl ConfigOption "domain" }}/docs
  statusInformers:
    - deployment/{{repl ConfigOption "namePrefix" }}-spline-reticulator
    - deployment/{{repl ConfigOption "namePrefix" }}-api-recombinator
    - deployment/{{repl ConfigOption "namePrefix" }}-spaghetti-saucer
```
