### ISSUE TITLE
Add a way to include helm chart value keys determined at runtime

### ISSUE THREAD

**Issue by laverya** [replicatedhq/kots#787]
Some helm charts provide a license file that is designed to be pasted into the values file, with multiple keys and values. To allow a vendor to use those helm charts with a customer-provided license, we would need some way to parse those files and split values to their individual keys.

Currently, individual values can be templated in, but if license_file is properly formatted json here:

```
apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: something
spec:
  chart:
    name: something

  values:
    data: | 
       repl{{ ConfigOptionData `license_file`}}
```

it will be treated as a string and not as subkeys of `data`.
