### ISSUE TITLE
Unable to create link that works for kURL and existing clusters

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kots#818]
I've defined application resources as
```
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: myapp
spec:
  title: MyApp
  ports:
  - serviceName: myapp
    servicePort: 8080
    localPort: 8080
    applicationUrl: http://myapp
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: myapp
spec:
  descriptor:
    links:
    - description: MyApp
      url: http://myapp
```

This link (sometimes) works when I run `kubectl kots admin-console`, but I don't see any way to use it with [kURL](https://kots.io/kotsadm/installing/installing-embedded-cluster).

I'd like to be able to provide links for
- the ingresses my application has configured
- when connected via `kots admin-console` (i.e. over a forwarded port), also add the current port-forwarded link

Templating seems to get partway towards this goal.
