### ISSUE TITLE
Strange template rendering YAML errors

### ISSUE THREAD

**Issue by MikaelSmith** [replicatedhq/kots#823]
Given a config like this (at `manifests/config.yaml`)
```
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config
spec:
  groups:
  - name: setup
    title: Setup
    items:
    - name: hostname
      type: text
      title: Hostname
      required: true
    - name: enable_ingress
      type: bool
      default: "1"
    - name: tls_cert_method
      type: select_one
      title: TLS certificate method
      default: self_signed
      items:
      - name: self_signed
        title: Generate self-signed certificate (expires in 365 days)
      - name: manual
        title: Provide certificates
      - name: auto
        title: Automatic generator (such as cert-manager)
      when: '{{repl ConfigOptionEquals "enable_ingress" "1"}}'
    - name: ingress_certs
      type: textarea
      hidden: true
      value: repl{{$ca := genCA "ingress-ca" 365}}repl{{$cert := genSignedCert (ConfigOption "hostname") nil (list (ConfigOption "hostname") (print "*." (ConfigOption "hostname"))) 365 $ca}}repl{{cat ($ca.Cert | b64enc) ($cert.Cert | b64enc) ($cert.Key | b64enc)}}
      when: '{{repl and (ConfigOptionEquals "enable_ingress" "1") (ConfigOptionEquals "tls_cert_method" "self_signed")}}'
    - name: self_ingress_ca
      type: textarea
      hidden: true
      value: repl{{(split " " (ConfigOption "ingress_certs"))._0 | b64dec}}
      when: '{{repl and (ConfigOptionEquals "enable_ingress" "1") (ConfigOptionEquals "tls_cert_method" "self_signed")}}'
    - name: self_ingress_cert
      type: textarea
      hidden: true
      value: repl{{(split " " (ConfigOption "ingress_certs"))._1 | b64dec}}
      when: '{{repl and (ConfigOptionEquals "enable_ingress" "1") (ConfigOptionEquals "tls_cert_method" "self_signed")}}'
    - name: self_ingress_key
      type: textarea
      hidden: true
      value: repl{{(split " " (ConfigOption "ingress_certs"))._2 | b64dec}}
      when: '{{repl and (ConfigOptionEquals "enable_ingress" "1") (ConfigOptionEquals "tls_cert_method" "self_signed")}}'
```

rendering it with
```
kubectl kots pull cd4pe --local-path manifests --rootdir output --exclude-admin-console --exclude-kots-kinds=false
```

produces an error in `installation.yaml`
```
  yamlErrors:
  - error: 'yaml: line 39: could not find expected '':'''
    path: config.yaml
```

It seems to render as valid YAML when I look at `base/userdata/config.yaml`.

Note that I have seen some strange fragility in rendering this when I change it, so I'm going to keep exploring that. It's a more complicated repro than I think it needs to be because of that.

**Comment by emosbaugh** [comment]
The errors will be hidden from the ui in this pr https://github.com/replicatedhq/kots/pull/819

We are currently working on fixing the underlying issue so that the config.yaml does not trigger that error

**Comment by emosbaugh** [comment]
Resolved by #824

**Comment by MikaelSmith** [comment]
I simplified the example
```
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: config
spec:
  groups:
  - name: setup
    title: Setup
    items:
    - name: ingress_ca
      type: textarea
      value: repl{{TLSCert "cert" "foo.com" nil nil 365 }}
    - name: other
      type: textarea
```

I still get an error in yamlErrors when I do `kots pull` on it
```
apiVersion: kots.io/v1beta1
kind: Installation
metadata:
  creationTimestamp: null
  name: replicated-kots-app
spec:
  encryptionKey: UZVUwZA1XlguhKqhi2L4X1FdV9OD1xg6rzDna29XcEMnQfIG
  yamlErrors:
  - error: 'yaml: line 14: could not find expected '':'''
    path: config.yaml
status: {}
```

I'm using a build based on a64f3e67ec8d05ad2b92d2735c3f66fa44b8ae97 to test.
