### ISSUE TITLE
Non deterministic scheduling when running on hybrid architecture clusters

### ISSUE THREAD

**Issue by marccampbell** [replicatedhq/kots#896]
Currently, KOTS only ships amd64 images. When running a `kots install` on a cluster that has both arm64 and amd64 images, the scheduling and placement is unreliable.

Kubernetes nodes have labels to help with this.
```
kubernetes.io/os=linux
kubernetes.io/arch=amd64
```

KOTS should set these labels in affinity when scheduling, at least until there are other OS and architecture images available.

For example, adding the following to the `kotsadm` pod would help:

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/os"
                operator: In
                values:
                - linux
              - key: "kubernetes.io/arch"
                operator: In
                values:
                - amd64
```

When this happens, the only way to get KOTS to reliably schedule is to manually edit the deployments and statefulsets to add these label selectors.
